# Generated by Django 6.0.5 on 2026-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('completed', 'Completado'), ('error', 'Error')], default='running', max_length=20)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('total_transactions', models.BigIntegerField(blank=True, null=True)),
                ('total_clients', models.BigIntegerField(blank=True, null=True)),
                ('total_units', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['category_id'],
            },
        ),
    ]
